### ISSUE TITLE
Many source file directories, `src-dir` not supported

### ISSUE THREAD

**Issue by zchrissirhcz** [psycofdj/coverxygen#22]
Hi, coverxygen developers

I'm using doxygen together with coverxygen for document coverage report. The C++ project I'm using is big, containing many modules, thus header files are distributed in each module's own including directory.

Here comes the question, coverxygen's `--src-dir` option does not support multiple directories?

**Comment by zchrissirhcz** [comment]
To make it clear, my Doxygen configuration file looks like the following, specified `STRIP_FROM_PATH` and `INPUT` for many source directories:
```
STRIP_FROM_PATH = @CMAKE_SOURCE_DIR@/src/rock_imgproc \
                  @CMAKE_SOURCE_DIR@/src/rock_video \
                  @CMAKE_BINARY_DIR@/include
BUILTIN_STL_SUPPORT = YES
TYPEDEF_HIDES_STRUCT = YES
EXTRACT_ALL = YES
EXTRACT_STATIC = YES
SHOW_GROUPED_MEMB_INC = YES
SORT_BRIEF_DOCS = YES
SORT_MEMBERS_CTORS_1ST = YES
QUIET = YES
ENABLE_PREPROCESSING = YES
INPUT = @CMAKE_CURRENT_SOURCE_DIR@/root.md \
        @CMAKE_CURRENT_SOURCE_DIR@/faq.md \
        @CMAKE_SOURCE_DIR@/src/rock_imgproc \
        @CMAKE_SOURCE_DIR@/src/rock_video
```

**Comment by psycofdj** [comment]
Indeed, multiple source directories are not yet supported and a PR on this is more than welcome.

However, I might be a little bit tricky to do:
- `--src-dir` is used to find the actual file that defines a symbol
- that is done by parsing the `location` attribute in the xml files as in [here](https://github.com/psycofdj/coverxygen/blob/9c25bb1ab64f0f5666ee7d3509c6fca72c638b8b/coverxygen/test/data/enum.xml#L43) then resolving the actual file path using `--src-dir`.
- I fear that having multiple `--src-dir` to operate this path resolution *could* introduce ambiguities between similar symbols defined in file with the same name

Question: what does doxygen output in the `location` attribute in case of multiple input-directories with `STRIP_FROM_PATH` directives ?

**Comment by zchrissirhcz** [comment]
Thanks for you response.

In case of multiple input-directories with `STRIP_FROM_PATH` directives, the `location` looks like this:
```xml
        <location file="rock/arr.hpp" line="30" column="5" bodyfile="rock/arr.hpp" bodystart="31" bodyend="39"/>
```
Among which, `rock/arr.hpp` 's absolute path is `/home/zz/work/rock_project/src/rock_core/rock/arr.hpp`, and `/home/zz/work/rock_project/src` is striped.

Actually I debugged with the coverxygen source code, and also try to find the `rock_core` subdirectory in all the generated xml directory, but not found valid ones. I personally think this should not be an coverxygen issue, it is more like to be resolved in doxygen official functionality, i.e. when specifying `STRIP_FROM_PATH`, can still keep absolute path.

Currently my solution is by loading, modifying and saving one existing `Doxyfile` config file, and comment out the `STRIP_FROM_PATH` line(s), save as an new configure file, then generate document coverage based on this new configure file.

**Comment by psycofdj** [comment]
> Among which, `rock/arr.hpp` 's absolute path is `/home/zz/work/rock_project/src/rock_core/rock/arr.hpp`, and `/home/zz/work/rock_project/src` is striped.

I'm puzzled:
- where are the `rock_imgproc` and `rock_video` directories ? 
- isn't `/home/zz/work/rock_project/src/rock_core` that is stripped instead of `/home/zz/work/rock_project/src` ?
- in that case, I assume that your last doxygen sample config was only and extract and that in reality you also have `@CMAKE_SOURCE_DIR@/src/rock_core` in both `INPUTS` and `STRIP_FROM_PATH`. Am I right ?

**Comment by psycofdj** [comment]
In any case, I also think that doxygen should keep track of stripped path in their xml output even if I'm absolutely not surprised that its not the current behavior.

**Comment by zchrissirhcz** [comment]
> > Among which, `rock/arr.hpp` 's absolute path is `/home/zz/work/rock_project/src/rock_core/rock/arr.hpp`, and `/home/zz/work/rock_project/src` is striped.
> 
> I'm puzzled:
> 
>     * where are the `rock_imgproc` and `rock_video` directories ?
> 
>     * isn't `/home/zz/work/rock_project/src/rock_core` that is stripped instead of `/home/zz/work/rock_project/src` ?
> 
>     * in that case, I assume that your last doxygen sample config was only and extract and that in reality you also have `@CMAKE_SOURCE_DIR@/src/rock_core` in both `INPUTS` and `STRIP_FROM_PATH`. Am I right ?

Yes, your assumption is right, I have `@CMAKE_SOURCE_DIR@/src/rock_core` in both `INPUTS` and `STRIP_FROM_PATH`.

Since we have agree on the expected behavior of doxygen itself, now I close this issue.
Thanks anyway.

**Comment by psycofdj** [comment]
Alright. If you find any clever way to modify coverxygen in order to cover your need, feel free to create a PR. 

Even if we agree that the "problem" is on doxygen side, I'll understand that it easier to modify this little tool than working to change doxygen behavior.

**Comment by zchrissirhcz** [comment]
Yes, I should find a clever way... I still tried with a search in doxygen source code and git commit history, and get some idea.

I think with `STRIP_FROM_PATH` specified, doxygen generated xml file won't contain absolute path, in the `location file=xxx` xml node property. Corresponding source code is:

https://github.com/doxygen/doxygen/blob/master/src/xmlgen.cpp#L1009-L1012

![图片](https://user-images.githubusercontent.com/3831847/144592641-d8e2689f-b233-4f3a-8abd-318a07897d1e.png)

Actually, the wrapped `stripFromPath()` is introduced in a Pull Request : https://github.com/doxygen/doxygen/pull/331 , with no comments in that PR. I tried remove the `stripFromPath()` in the C++ file, re-compile and install my modified doxygen, re-generated  document files(html, xml), and generate document report with coverxygen, it is what I expected to see:

1. The html document keeps unchanged. Each public function/class with `addtogroup`, still correctly show stripped header files as I expected.
2. The document coverage report relied `genhtml` command, run OK, without error anymore, since `location file=/absolute/path/to/file` is correct path.
