### ISSUE TITLE
Feature Request: Markdown summary table output

### ISSUE THREAD

**Issue by EngJay** [psycofdj/coverxygen#23]
A Markdown summary table output option would make this more easily usable in CI workflows by allowing the output to be piped directly to PR auto-comments.

**Comment by psycofdj** [comment]
Hello @EngJay 
I agree, this would be a nice feature. Would you mind creating a pull-request about this ?

For the moment I don't have time for developing new things on this repository. However, I will continue its maintenance and be happy to merge and release a new version.

**Comment by EngJay** [comment]
@psycofdj Hi there! I'll take a look this weekend to see if I can fit it in. I'm also seeing a lot of false negatives but I've yet to determine if it's something to do with how we're formatting our doc comments or what, so I haven't opened an issue.
