### ISSUE TITLE
Releases are not tagged in git

### ISSUE THREAD

**Issue by antoniovazquezblanco** [psycofdj/coverxygen#25]
Although this may not be such a big deal to be reported as a "bug", it is a requirement to correctly describe package versioning in Archlinux AUR packages in an automated way. It would be a nice to have feature!

Thanks!

**Comment by psycofdj** [comment]
I don't understand, there is a git tag and a github release associated to every release
Did I missed something ? https://github.com/psycofdj/coverxygen/releases

**Comment by antoniovazquezblanco** [comment]
Wow, now I see there are. I will review my AUR package scripts... Sorry and thanks!

**Comment by psycofdj** [comment]
you're welcome :+1:
