### ISSUE TITLE
Integration with codecov.io

### ISSUE THREAD

**Issue by junghans** [psycofdj/coverxygen#4]
See codecov/support#364, in short coverxygen can be used to get doxygen coverage numbers on codecov.io by simply adding something like:
```
make doxygen
python -m coverxygen --xml-dir xml/ --src-dir . --output doxygen.coverage.info
bash <(curl -s https://codecov.io/bash) -R . -F doxygen -X gcov -f doxygen.coverage.info
```

**Comment by psycofdj** [comment]
Thanks for the tip !
I'm glad you managed to make it work with [codecov.io](https://codecov.io/).

@junghans I see you're working with C/C++ code. You might by interested by [psycofdj/xtdmake](https://github.com/psycofdj/xtdmake) [(link to doc)](http://xtdmake.readthedocs.io/en/latest/) to generate code quality reports from cmake's targets.
